### ISSUE TITLE
Feature Idea: Undo Last Commit

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-tinygit#11]
### Feature Requested

Would be helpful to quickly undo the last commit:

`git reset --soft HEAD~1`

Could maybe even have an optional parameter that does a hard reset:

`git reset --hard HEAD~1`

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the [Non-Goals section of the README](..#non-goals).

**Comment by chrisgrieser** [comment]
I also thought about this one, but decided not to implement it, since you can already do that with telescope's git_commits.

**Comment by kevintraver** [comment]
Ah, yes I see now you can do that in telescope.

Would you still be open to also implementing it in **nvim-tinygit**?

Currently I open up a terminal use [git-extras](https://github.com/tj/git-extras) `undo` command. 

I was just thinking it would be nice to be able to set a **nvim-tinygit** keymap and not have to open telescope or use a terminal.

**Comment by kevintraver** [comment]
Could be something simple like this: #12
