### ISSUE TITLE
Feature Request: Allow passing `pullBefore` flag in `smartCommit` function

### ISSUE THREAD

**Issue by aegonz** [chrisgrieser/nvim-tinygit#15]
### Feature Requested

Allow passing `pullBefore` flag in `smartCommit` function

In the smartCommig function the following line hardcodes the `pullBefore` parameter to true.

```
-- push
if opts.pushIfClean and cleanAfterCommit then push { pullBefore = true } end
```

It would be helpful if the user was allowed to set that flag explicitly during `smartCommit`

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the [Non-Goals section of the README](..#non-goals).

**Comment by chrisgrieser** [comment]
Good point, added.
