### ISSUE TITLE
Feature Request: Opt-out of "stage all if nothing staged" behavior

### ISSUE THREAD

**Issue by alex35mil** [chrisgrieser/nvim-tinygit#18]
### Feature Requested

In amend functions, I think I would prefer to opt-out of "stage all if nothing staged". So it would be great to have an option to do so.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the [Non-Goals section of the README](..#non-goals).

**Comment by chrisgrieser** [comment]
I am not sure I follow how that would be useful?
- `amendOnlyMsg` does not stage anything
- `amendNoEdit` stages only if nothing is staged. If you do not want to stage all changes with it, you can just stage something manually, and `amendNoEdit` will not stage anything. The only scenario not supported by `amendNoEdit` is an empty amend, which kind of does not make sense.

**Comment by alex35mil** [comment]
The use-case I just faced is that I thought I staged some changes that I hadn't and with `forcePushIfDiverged = true` I accidentally staged all, amended, and pushed everything.

I would prefer to cancel the operation with a warning that nothing is staged in this case.

**Comment by chrisgrieser** [comment]
I see, as a safety net, that makes sense.

Added `stageAllIfNothingStaged` options for `amendNoEdit`.
