### ISSUE TITLE
[Bug]: Input from prompt does not get saved

### ISSUE THREAD

**Issue by kevintraver** [chrisgrieser/nvim-tinygit#2]
### Bug Description

This line seems to be causing problems:

https://github.com/chrisgrieser/nvim-tinygit/blob/fd364977863e2b4f56f7ea67b8107e69e2933c21/lua/tinygit.lua#L186

When removing it, the input from the prompt gets saved.

### To Reproduce

1. Open the commit dialog.
2. Type in a commit message.
3. Press Enter.

Nothing happens.

### neovim version

```Text
0.9.2
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thx, that was actually an oudated workaround. removed and thus fixed.
