### ISSUE TITLE
Question: May I have this color scheme's name? Thanks!

### ISSUE THREAD

**Issue by bitterteasweetorange** [chrisgrieser/nvim-tinygit#3]
### Feature Requested

![image](https://github.com/chrisgrieser/nvim-tinygit/assets/115888595/281771f7-7224-449a-a135-b0a1dcc6c9e3)

### Checklist

- [ ] The feature would be useful to more users than just me.
- [x] I have read the [Non-Goals section of the README](..#non-goals).

**Comment by chrisgrieser** [comment]
It's the dawn fox variant of night fox.nvim

**Comment by bitterteasweetorange** [comment]
thanks!
