### ISSUE TITLE
Feature Request: force push with lease

### ISSUE THREAD

**Issue by Swanncastel** [chrisgrieser/nvim-tinygit#4]
### Feature Requested

Add the ability to force push with lease

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the [Non-Goals section of the README](..#non-goals).

**Comment by Swanncastel** [comment]
I've found a workaround : never force push on commit and amend, then push with force and pullBefore BUT the code uses the command `git pull;` be careful, if the git pull fails, we are going to force push without the remote code.
`git pull &&` might be better.

**Comment by Swanncastel** [comment]
Actually this is not even working, I have to force push with lease from my terminal

**Comment by chrisgrieser** [comment]
yeah, I am not much of an expert on all the git push/pull options, so feel free to make a PR if you have looked through the code already anyway?

**Comment by Swanncastel** [comment]
Hi, I'm going to look at it when I have some time

**Comment by chrisgrieser** [comment]
okay, I read up on this and it seems `--force-with-lease` is pretty much always the safer option, so I just switched it to `--force-with-lease` throughout.
