### ISSUE TITLE
[Bug]: Default max witdth for notify is nil, so it breaks commit command

### ISSUE THREAD

**Issue by dansdantas** [chrisgrieser/nvim-tinygit#6]
### Bug Description

https://github.com/chrisgrieser/nvim-tinygit/blob/6b133f56d7b61a684db7ae2c9e199f306af4ca8c/lua/tinygit/commands/commit-and-amend.lua#L191-L198

When defining width for preview, if nvim-notify is installed it queries `max_width` attribute so it doesn't overflow. On default config `max_width` is set to nil, and even if set to nil by user, it breaks this function because it can't remove 2 from nil(not sure if was changed recently)

https://github.com/rcarriga/nvim-notify/blob/1576123bff3bed67bc673a3076e591abfe5d8ca9/lua/notify/config/init.lua#L20-L44

### To Reproduce

1. Install both tinygit and nvim-notify
2. call tinygit smartCommit function

### neovim version

```Text
NVIM v0.10.0-dev-2037+ge09adfdcf
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thx, fixed

**Comment by kevintraver** [comment]
I am still seeing this issue with the latest version of both plugins.

**Comment by chrisgrieser** [comment]
@kevintraver works on my end, with and without the `max_width` config from nvim-notify.

Could you please post the error you are getting?

**Comment by kevintraver** [comment]
`msg_show.emsg E5108: Error executing lua: .../nvim-tinygit/lua/tinygit/commands/commit-and-amend.lua:193: attempt to perform arithmetic on field 'max_width' (a function value)`

If I set `max_width` in _nvim-notify_ then I don't get the error.

**Comment by chrisgrieser** [comment]
That is very weird, I only ever get number of nil for `max_width`.

Can only guess that some nvim-notify setting makes the `max_width` a function to be dynamic. Anyway, should be fixed

**Comment by kevintraver** [comment]
Yes it does appear fixed now. Thanks!

**Comment by kevintraver** [comment]
Ok, just for reference, Im using LazyVim, which is where that setting is coming from:

https://github.com/LazyVim/LazyVim/blob/0107a1079be7fb92f7d5b7e2c40818f47cf425d9/lua/lazyvim/plugins/ui.lua#L21-L23

**Comment by chrisgrieser** [comment]
Oh I see, thanks!
